// =============================================================================
//                        !!! DO NOT EDIT THIS FILE !!!
// =============================================================================

#pragma once
#include <cstdint>
#include <vector>

struct MemSimResult {
  int64_t n_pages_requested;
  int64_t max_free_partition_size;
};

struct Request {
  int tag;
  int size;
};

void mem_sim(int64_t page_size, const std::vector<Request> & requests, MemSimResult & result);