// =============================================================================
//                        !!! DO NOT EDIT THIS FILE !!!
// =============================================================================
#pragma once
#include <vector>

void fat_sim(const std::vector<long> & fat, long & longest_file_blocks, long & unused_blocks);
